### ISSUE TITLE
Tag in issue/PRs

### ISSUE THREAD

**Issue by yungyuc** [ThreeMonth03/Conjugate-Gradient-Method-library#1]
https://github.com/ThreeMonth03/Conjugate-Gradient-Method-library

It's good to see your making progress.  Hope you can have PR for code review soon.

**Comment by yungyuc** [comment]
@ThreeMonth03 You seem to make good progress.  That is great.  Could you please try to file some PRs like how https://github.com/Yvonne-ul6u45p/ContiguousArray-MultiDim-Index-Calculation/pull/2 was done?  That helps me to take a look at what you are doing and provide you comments.

**Comment by ThreeMonth03** [comment]
Ok, I understand. Thank you for your suggestion. I hope I do the right thing.

**Comment by yungyuc** [comment]
Don't worry about making mistakes.  Make mistakes as many and fast as you can.

**Comment by ThreeMonth03** [comment]
@yungyuc  
I think I preliminary finish the project except the readme.md.
Here is the PR. Thank you for your suggestion.
(PRs)[https://github.com/ThreeMonth03/Conjugate-Gradient-Method-library/pull/3]
